### ISSUE TITLE
[discussion] expose color classes?

### ISSUE THREAD

**Issue by yoshuawuyts** [Kriesse/dat-colors#2]
Maybe it could be an idea to create a bunch of color classes in addition to the variables. Something like:
```js
var css = require('sheetify')
var html = require('bel')

css('dat-colors/classes')

var el = html`
  <main class="blue b--black bg-white">hi</main>
`
```

Not sure what the right words for these are; I'm sure you have a better idea on how to structure these. But I think it might be cool to have more micro classes we can apply to elements :D Let me know what you think :sparkles:

ref https://github.com/datproject/dat-desktop/issues/103

**Comment by Kriesse** [comment]
@yoshuawuyts yes agreed!

How would I expose the classes tho? So that `css('dat-colors/classes')` would work? Do I just add a file classes.css?

**Comment by yoshuawuyts** [comment]
Yup, exactly :D

**Comment by yoshuawuyts** [comment]
woot, done!
